name: final_project
description: Final project for LinceTech Academy.


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.0+3
  intl: ^0.17.0
  provider:
  shared_preferences:
  page_transition: ^2.0.9
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/PoppinsLight-Light.ttf

